# Generated by Django 3.2.1 on 2021-05-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshowpost',
            name='uploads',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='image'),
        ),
    ]
