# Generated by Django 3.2.1 on 2021-05-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0005_aboutpost_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('email', models.CharField(max_length=300, verbose_name='email')),
                ('subject', models.CharField(max_length=1000, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
            ],
        ),
    ]
